### ISSUE TITLE
ver 7.0.0 jakarta.mail.Session breaking changes on application server

### ISSUE THREAD

**Issue by sysmat** [bbottema/simple-java-mail#369]
- On application server(glassfish, payara, ...), JavaMail Sessions is:
> a JavaMail session resource represents a mail session in the JavaMail API.
- with this change, you broke backward compatibility, it should still have `usingSession` which uses `javax.mail.Session`
- it is very common to use `@Resource`  for `javax.mail.Session`
- maybe would be better to have extra `usingJakartaSession`  for `jakarta.mail.Session`

**Comment by sysmat** [comment]
even if I use:

```java
@Resource(name = "mail/skala")
private javax.mail.Session mailSession;

jakarta.mail.Session s = jakarta.mail.Session.getDefaultInstance(mailSession.getProperties());
 MailerBuilder.usingSession(s)
                                .async()
                                .withThreadPoolSize(3)
                                .withProperty("mail.smtp.timeout", 10 * 1000)
                                .withProperty("mail.smtp.connectiontimeout", 10 * 1000)
                                .buildMailer();
```

I got error:

```
Error:java.lang.VerifyError: Instruction type does not match stack map
Exception Details:
  Location:
    org/simplejavamail/converter/internal/mimemessage/MimeMessageProducer.populateMimeMessage(Lorg/simplejavamail/api/email/Email;Ljakarta/mail/Session;Lorg/simplejavamail/api/mailer/config/Pkcs12Config;)Ljakarta/mail/internet/MimeMessage; @157: aload
  Reason:
    Type 'org/simplejavamail/converter/internal/mimemessage/ImmutableDelegatingSMTPMessage' (current frame, locals[4]) is not assignable to 'jakarta/mail/internet/MimeMessage' (stack map, locals[4])
  Current Frame:
    bci: @157
    flags: { }
    locals: { 'org/simplejavamail/converter/internal/mimemessage/MimeMessageProducer', 'org/simplejavamail/api/email/Email', 'jakarta/mail/Session', 'org/simplejavamail/api/mailer/config/Pkcs12Config', 'org/simplejavamail/converter/internal/mimemessage/ImmutableDelegatingSMTPMessage' }
    stack: { }
  Stackmap Frame:
    bci: @157
    flags: { }
    locals: { 'org/simplejavamail/converter/internal/mimemessage/MimeMessageProducer', 'org/simplejavamail/api/email/Email', 'jakarta/mail/Session', 'org/simplejavamail/api/mailer/config/Pkcs12Config', 'jakarta/mail/internet/MimeMessage' }
    stack: { }
  Bytecode:
    0x0000000: 2b12 02b8 0003 572c 1204 b800 0357 bb00
    0x0000010: 0559 2a2c 2bb7 0006 3a04 2b19 04b8 0007
    0x0000020: 2b19 04b8 0008 2b19 04b8 0009 2b19 04b8
    0x0000030: 000a 2a19 042b b600 0b2b 1904 b800 0c19
    0x0000040: 042b b600 0db8 000e bb00 0f59 b700 10b6
    0x0000050: 0011 c000 0fb6 0012 b800 1399 0012 b800
    0x0000060: 142c 1904 2b2d b900 1505 003a 042b b600
    0x0000070: 16b8 0017 9a00 10b8 0018 1904 2bb9 0019
    0x0000080: 0300 3a04 2bb6 001a c600 15bb 001b 5919
    0x0000090: 042b b600 1ab6 001c b700 1d3a 0419 04b0
    0x00000a0:                                        
  Stackmap Table:
    append_frame(@109,Object[#63])
    same_frame(@132)
    same_frame(@157)
```

backward is broken, when not using standard

**Comment by bbottema** [comment]
I'm not sure why you think a major release should break backwards compatibility. JavaMail is obsolete and not maintained anymore for years now and has been migrated to Jakarta. So obviously I cannot guarantee backwards compatibility, similarly to how the switch to Java8 made sure Simple Java Mail won't work on 1.7 JVM's anymore. Maintaining support for both JavaMail and JakartaMail is not going to be possible.

However, I may consider a new module that helps migrating from JavaMail to JakartaMail. Like a conversion between Session objects. I will think about this.

**Comment by bbottema** [comment]
Fyi, I just published the [migration notes for 7.0.0](https://www.simplejavamail.org/migration-notes-7.0.0.html) that mentions this as well.

**Comment by sysmat** [comment]
Even if I build jakarta session still getting error:
- java:

```java
Properties props = new Properties();
props.put("mail.smtp.host", "mail.arnes.si");             
MailerBuilder.usingSession(Session.getInstance(props))
                      .async()
                      .withThreadPoolSize(3)
                      .withProperty("mail.smtp.timeout", 10 * 1000)
                      .withProperty("mail.smtp.connectiontimeout", 10 * 1000)
                      .buildMailer();

```
- error:
```
s.a.p.implementations.SendMailImpl.closeMailerLogResponse(107) - func=sendFeedback:Exception=java.lang.VerifyError: Instruction type does not match stack map
Exception Details:
  Location:
    org/simplejavamail/converter/internal/mimemessage/MimeMessageProducer.populateMimeMessage(Lorg/simplejavamail/api/email/Email;Ljakarta/mail/Session;Lorg/simplejavamail/api/mailer/config/Pkcs12Config;)Ljakarta/mail/internet/MimeMessage; @157: aload
  Reason:
    Type 'org/simplejavamail/converter/internal/mimemessage/ImmutableDelegatingSMTPMessage' (current frame, locals[4]) is not assignable to 'jakarta/mail/internet/MimeMessage' (stack map, locals[4])
  Current Frame:
    bci: @157
    flags: { }
    locals: { 'org/simplejavamail/converter/internal/mimemessage/MimeMessageProducer', 'org/simplejavamail/api/email/Email', 'jakarta/mail/Session', 'org/simplejavamail/api/mailer/config/Pkcs12Config', 'org/simplejavamail/converter/internal/mimemessage/ImmutableDelegatingSMTPMessage' }
    stack: { }
  Stackmap Frame:
    bci: @157
    flags: { }
    locals: { 'org/simplejavamail/converter/internal/mimemessage/MimeMessageProducer', 'org/simplejavamail/api/email/Email', 'jakarta/mail/Session', 'org/simplejavamail/api/mailer/config/Pkcs12Config', 'jakarta/mail/internet/MimeMessage' }
    stack: { }
  Bytecode:
    0x0000000: 2b12 02b8 0003 572c 1204 b800 0357 bb00
    0x0000010: 0559 2a2c 2bb7 0006 3a04 2b19 04b8 0007
    0x0000020: 2b19 04b8 0008 2b19 04b8 0009 2b19 04b8
    0x0000030: 000a 2a19 042b b600 0b2b 1904 b800 0c19
    0x0000040: 042b b600 0db8 000e bb00 0f59 b700 10b6
    0x0000050: 0011 c000 0fb6 0012 b800 1399 0012 b800
    0x0000060: 142c 1904 2b2d b900 1505 003a 042b b600
    0x0000070: 16b8 0017 9a00 10b8 0018 1904 2bb9 0019
    0x0000080: 0300 3a04 2bb6 001a c600 15bb 001b 5919
    0x0000090: 042b b600 1ab6 001c b700 1d3a 0419 04b0
    0x00000a0:                                        
  Stackmap Table:
    append_frame(@109,Object[#63])
    same_frame(@132)
    same_frame(@157)
```

**Comment by bbottema** [comment]
I have no idea what that server is trying to do, what dependencies are loaded and in which order. That's not even a stack trace but some error dump that doesn't tell me anything. No clue what going on there, sorry.

**Comment by sysmat** [comment]
- it is cacth from exception
```java
try {
    CompletableFuture<Void> response = mailer.sendMail(email, true);
    response.get();
} catch (InterruptedException | ExecutionException ex) {
      log.error("Exception={}", ex.getMessage());
}
```

**Comment by sysmat** [comment]
- Jakrate EE is not Java EE, it is a great library but we will probably migrate to something else which use standard 
- from foundation:
> Eclipse GlassFish 5.1.0 is a Jakarta EE 8 Compatible Implementation.
> Eclipse GlassFish 6.0.0 is a Jakarta EE 9 Compatible Implementation and and older release of Eclipse GlassFish.

so this approach is kind of vendor locking

**Comment by bbottema** [comment]
> ```java
> log.error("Exception={}", ex.getMessage());
> ```

So this doesn't actually log the exception, it cuts it out and only logs the last exception's _message_.

> Jakrate EE is not Java EE, it is a great library but we will probably migrate to something else which use standard

I have no idea what you're saying here. Jakarta Mail is _the_ standard mailing library for java. It is the official successor to the abandoned JavaMail which was written by Sun itself. Jakarta is nothing more than the hosting platform and Jakarta Mail has nothing to do with EE or other Jakarta dependencies (other than Jakarta activation).

Other than a few very limited custom mailing libraries there's nothing else out there (certainly nothing _standard_).

**Comment by sysmat** [comment]
the namespace or packining from javax to jakarta is changed

**Comment by sysmat** [comment]
yes as you are saying jakarta is successor

**Comment by bbottema** [comment]
OK... well, good luck!
