### ISSUE TITLE
Project does not build from GitHub.

### ISSUE THREAD

**Issue by dormitionskete** [bbottema/simple-java-mail#96]
The project will not build using source cloned from GitHub for me, or for another developer I asked to try to build it.  One of the tests fails.

`cd /Users/frpeter/NetBeansProjects/simple-java-mail; JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home "/Applications/NetBeans/NetBeans 8.2.app/Contents/Resources/NetBeans/java/maven/bin/mvn" install
Scanning for projects...
Inspecting build with total of 1 modules...
Installing Nexus Staging features:
  ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
                                                                        
------------------------------------------------------------------------
Building Simple Java Mail 4.3.1-SNAPSHOT
------------------------------------------------------------------------

--- maven-resources-plugin:2.5:resources (default-resources) @ simple-java-mail ---
[debug] execute contextualize
Using 'UTF-8' encoding to copy filtered resources.
Copying 3 resources

--- maven-compiler-plugin:3.5.1:compile (default-compile) @ simple-java-mail ---
Nothing to compile - all classes are up to date

--- assertj-assertions-generator-maven-plugin:2.0.0:generate-assertions (default) @ simple-java-mail ---

====================================
AssertJ assertions generation report
====================================

--- Generator input parameters ---

Generating AssertJ assertions for classes:
- org.simplejavamail.email.Email

--- Generator results ---

Directory where custom assertions files have been generated:
- /Users/frpeter/NetBeansProjects/simple-java-mail/target/generated-test-sources/assertj-assertions

Custom assertions files generated:
- /Users/frpeter/NetBeansProjects/simple-java-mail/target/generated-test-sources/assertj-assertions/org/simplejavamail/email/EmailAssert.java

Assertions entry point class has been generated in file:
- /Users/frpeter/NetBeansProjects/simple-java-mail/target/generated-test-sources/assertj-assertions/org/simplejavamail/email/Assertions.java

BddAssertions entry point class has been generated in file:
- /Users/frpeter/NetBeansProjects/simple-java-mail/target/generated-test-sources/assertj-assertions/org/simplejavamail/email/BddAssertions.java

SoftAssertions entry point class has been generated in file:
- /Users/frpeter/NetBeansProjects/simple-java-mail/target/generated-test-sources/assertj-assertions/org/simplejavamail/email/SoftAssertions.java

JUnitSoftAssertions entry point class has been generated in file:
- /Users/frpeter/NetBeansProjects/simple-java-mail/target/generated-test-sources/assertj-assertions/org/simplejavamail/email/JUnitSoftAssertions.java

--- maven-resources-plugin:2.5:testResources (default-testResources) @ simple-java-mail ---
[debug] execute contextualize
Using 'UTF-8' encoding to copy filtered resources.
Copying 5 resources

--- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ simple-java-mail ---
Changes detected - recompiling the module!
Compiling 23 source files to /Users/frpeter/NetBeansProjects/simple-java-mail/target/test-classes

--- maven-surefire-plugin:2.19.1:test (default-test) @ simple-java-mail ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.simplejavamail.converter.internal.mimemessage.MimeMessageHelperTest
Running org.simplejavamail.converter.internal.mimemessage.NamedDataSourceTest
Running org.simplejavamail.email.EmailBuilderUsingDefaultsFromPropertyFileTest
Running org.simplejavamail.email.EmailBuilderTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.795 sec - in org.simplejavamail.converter.internal.mimemessage.NamedDataSourceTest
Running org.simplejavamail.email.EmailTest
Running org.simplejavamail.internal.util.MiscUtilTest
Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.738 sec - in org.simplejavamail.internal.util.MiscUtilTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.976 sec <<< FAILURE! - in org.simplejavamail.email.EmailBuilderUsingDefaultsFromPropertyFileTest
testBuilderSimpleBuildWithStandardEmail(org.simplejavamail.email.EmailBuilderUsingDefaultsFromPropertyFileTest)  Time elapsed: 3.602 sec  <<< FAILURE!
org.junit.ComparisonFailure: 
expected:<...itionNotificationTo=[true,
		dispositionNotificationTo=Recipient{name='null', address='simple@address.com', type=null},
	useReturnReceiptTo=true,
		returnReceiptTo=Recipient{name='Complex Email', address='simple@address.com', type=null},
	headers={dummyHeader=dummyHeaderValue]},
	embeddedImages=[...> but was:<...itionNotificationTo=[false,
		dispositionNotificationTo=null,
	useReturnReceiptTo=false,
		returnReceiptTo=null,
	headers={]},
	embeddedImages=[...>
	at org.simplejavamail.email.EmailBuilderUsingDefaultsFromPropertyFileTest.testBuilderSimpleBuildWithStandardEmail(EmailBuilderUsingDefaultsFromPropertyFileTest.java:34)

Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.061 sec - in org.simplejavamail.email.EmailBuilderTest
Running org.simplejavamail.mailer.internal.mailsender.MailSenderTest
Running org.simplejavamail.mailer.MailerLiveTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.054 sec - in org.simplejavamail.email.EmailTest
Running org.simplejavamail.mailer.MailerTest
Running org.simplejavamail.mailer.ProxyConfigTest
DEBUG: setDebug: JavaMail version 1.5.5
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.127 sec - in org.simplejavamail.mailer.internal.mailsender.MailSenderTest
16:02:21 [main] INFO  SMTPServer - SMTP server *:251 starting
16:02:21 [main] INFO  SMTPServer - SMTP server *:251 starting
Tests run: 3, Failures: 0, Errors: 2, Skipped: 1, Time elapsed: 3.015 sec <<< FAILURE! - in org.simplejavamail.mailer.MailerLiveTest
createMailSession_StandardDummyMail(org.simplejavamail.mailer.MailerLiveTest)  Time elapsed: 0.14 sec  <<< ERROR!
java.lang.RuntimeException: java.net.BindException: Permission denied
Caused by: java.net.BindException: Permission denied

createMailSession_OutlookMessageTest(org.simplejavamail.mailer.MailerLiveTest)  Time elapsed: 0.01 sec  <<< ERROR!
java.lang.RuntimeException: java.net.BindException: Permission denied
Caused by: java.net.BindException: Permission denied

DEBUG: setDebug: JavaMail version 1.5.5
16:02:21 [main] WARN  Mailer - Providing access to Session instance for emergency fall-back scenario. Please let us know why you need it.
16:02:21 [main] WARN  Mailer - 	>https://github.com/bbottema/simple-java-mail/issues
DEBUG: setDebug: JavaMail version 1.5.5
16:02:21 [main] WARN  Mailer - Providing access to Session instance for emergency fall-back scenario. Please let us know why you need it.
16:02:21 [main] WARN  Mailer - 	>https://github.com/bbottema/simple-java-mail/issues
16:02:21 [main] DEBUG MailSender - No proxy set, skipping proxy.
16:02:21 [main] WARN  Mailer - Providing access to Session instance for emergency fall-back scenario. Please let us know why you need it.
16:02:21 [main] WARN  Mailer - 	>https://github.com/bbottema/simple-java-mail/issues
16:02:21 [main] DEBUG MailSender - No proxy set, skipping proxy.
16:02:21 [main] DEBUG MailSender - No proxy set, skipping proxy.
16:02:21 [main] DEBUG MailSender - No proxy set, skipping proxy.
16:02:21 [main] DEBUG MailSender - No proxy set, skipping proxy.
16:02:21 [main] DEBUG MailSender - No proxy set, skipping proxy.
16:02:21 [main] DEBUG MailSender - No proxy set, skipping proxy.
16:02:21 [main] WARN  Mailer - Providing access to Session instance for emergency fall-back scenario. Please let us know why you need it.
16:02:21 [main] WARN  Mailer - 	>https://github.com/bbottema/simple-java-mail/issues
16:02:21 [main] WARN  Mailer - Providing access to Session instance for emergency fall-back scenario. Please let us know why you need it.
16:02:21 [main] WARN  Mailer - 	>https://github.com/bbottema/simple-java-mail/issues
16:02:21 [main] WARN  Mailer - Providing access to Session instance for emergency fall-back scenario. Please let us know why you need it.
16:02:21 [main] WARN  Mailer - 	>https://github.com/bbottema/simple-java-mail/issues
16:02:21 [main] WARN  Mailer - Providing access to Session instance for emergency fall-back scenario. Please let us know why you need it.
16:02:21 [main] WARN  Mailer - 	>https://github.com/bbottema/simple-java-mail/issues
16:02:21 [main] WARN  Mailer - Providing access to Session instance for emergency fall-back scenario. Please let us know why you need it.
16:02:21 [main] WARN  Mailer - 	>https://github.com/bbottema/simple-java-mail/issues
16:02:21 [main] WARN  Mailer - Providing access to Session instance for emergency fall-back scenario. Please let us know why you need it.
16:02:21 [main] WARN  Mailer - 	>https://github.com/bbottema/simple-java-mail/issues
DEBUG: setDebug: JavaMail version 1.5.5
16:02:21 [main] WARN  Mailer - Providing access to Session instance for emergency fall-back scenario. Please let us know why you need it.
16:02:21 [main] WARN  Mailer - 	>https://github.com/bbottema/simple-java-mail/issues
DEBUG: setDebug: JavaMail version 1.5.5
DEBUG: setDebug: JavaMail version 1.5.5
16:02:21 [main] WARN  Mailer - Providing access to Session instance for emergency fall-back scenario. Please let us know why you need it.
16:02:21 [main] WARN  Mailer - 	>https://github.com/bbottema/simple-java-mail/issues
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.479 sec - in org.simplejavamail.mailer.MailerTest
Running org.simplejavamail.mailer.ServerConfigTest
Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.934 sec - in org.simplejavamail.mailer.ProxyConfigTest
Running org.simplejavamail.util.ConfigLoaderTest
16:02:24 [main] DEBUG ConfigLoader - Property file not found on classpath, skipping config file
Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.875 sec - in org.simplejavamail.mailer.ServerConfigTest
simplejavamail.proxy.username: null
simplejavamail.proxy.username: override2
simplejavamail.proxy.username: override2
Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.662 sec - in org.simplejavamail.util.ConfigLoaderTest

Results :

Failed tests: 
  EmailBuilderUsingDefaultsFromPropertyFileTest.testBuilderSimpleBuildWithStandardEmail:34 expected:<...itionNotificationTo=[true,
		dispositionNotificationTo=Recipient{name='null', address='simple@address.com', type=null},
	useReturnReceiptTo=true,
		returnReceiptTo=Recipient{name='Complex Email', address='simple@address.com', type=null},
	headers={dummyHeader=dummyHeaderValue]},
	embeddedImages=[...> but was:<...itionNotificationTo=[false,
		dispositionNotificationTo=null,
	useReturnReceiptTo=false,
		returnReceiptTo=null,
	headers={]},
	embeddedImages=[...>
Tests in error: 
  MailerLiveTest.createMailSession_OutlookMessageTest » Runtime java.net.BindExc...
  MailerLiveTest.createMailSession_StandardDummyMail » Runtime java.net.BindExce...

Tests run: 91, Failures: 1, Errors: 2, Skipped: 1

------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 19.606s
Finished at: Tue Aug 15 16:02:24 MDT 2017
Final Memory: 25M/270M
------------------------------------------------------------------------
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project simple-java-mail: There are test failures.

Please refer to /Users/frpeter/NetBeansProjects/simple-java-mail/target/surefire-reports for the individual test results.
-> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
`

**Comment by dormitionskete** [comment]
These were the errors the other developer got.

[errors.txt](https://github.com/bbottema/simple-java-mail/files/1226568/errors.txt)

**Comment by bbottema** [comment]
Yes, I'm aware of this, since Travis reported to me just as I went to sleep:

https://travis-ci.org/bbottema/simple-java-mail/builds

Since the library isn't released though, even as SNAPSHOT, I reserve the right to have a broken build :)

Hopefully I'll have it fixed tonight. I plan on releasing a new version upcoming weekend with the new milestone.

**Comment by bbottema** [comment]
fixed

**Comment by dormitionskete** [comment]
[Errors-2017-0816-1037.txt](https://github.com/bbottema/simple-java-mail/files/1228895/Errors-2017-0816-1037.txt)


I just thought I'd let you know it still doesn't build.  Different errors now.

I'm just going to work with what I have that works, and wait for your next release to implement your suggestion about using the builder to reuse the common data.

I appreciate your help, though.

**Comment by bbottema** [comment]
Related to #91 and #97. Getting hotfix out ASAP

**Comment by bbottema** [comment]
Should be solved in 4.4.2, please check if you have some time (might take a few minutes to appear in Maven Central).
